# Generated by Django 2.2.2 on 2019-09-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itenerary_name', models.CharField(help_text='Refrence Name for Itenerary.', max_length=200)),
                ('itenerary_length', models.IntegerField(default=0)),
                ('head_1', models.CharField(max_length=200)),
                ('desc_1', models.TextField()),
                ('head_2', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_2', models.TextField(blank=True, null=True)),
                ('head_3', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_3', models.TextField(blank=True, null=True)),
                ('head_4', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_4', models.TextField(blank=True, null=True)),
                ('head_5', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_5', models.TextField(blank=True, null=True)),
                ('head_6', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_6', models.TextField(blank=True, null=True)),
                ('head_7', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_7', models.TextField(blank=True, null=True)),
                ('head_8', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_8', models.TextField(blank=True, null=True)),
                ('head_9', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_9', models.TextField(blank=True, null=True)),
                ('head_10', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_10', models.TextField(blank=True, null=True)),
                ('head_11', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_11', models.TextField(blank=True, null=True)),
                ('head_12', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_12', models.TextField(blank=True, null=True)),
                ('head_13', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_13', models.TextField(blank=True, null=True)),
                ('head_14', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_14', models.TextField(blank=True, null=True)),
                ('head_15', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_15', models.TextField(blank=True, null=True)),
                ('head_16', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_16', models.TextField(blank=True, null=True)),
                ('head_17', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_17', models.TextField(blank=True, null=True)),
                ('head_18', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_18', models.TextField(blank=True, null=True)),
                ('head_19', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_19', models.TextField(blank=True, null=True)),
                ('head_20', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_20', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
