# Generated by Django 2.2.2 on 2019-09-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='itenerary_length',
            new_name='itinerary_length',
        ),
        migrations.RenameField(
            model_name='itinerary',
            old_name='itenerary_name',
            new_name='itinerary_name',
        ),
    ]
