# Generated by Django 2.2.2 on 2019-09-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0002_auto_20190906_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'verbose_name_plural': 'Itineraries'},
        ),
    ]
