# Generated by Django 2.2.2 on 2019-09-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0003_auto_20190908_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.TextField()),
                ('is_active', models.BooleanField(default=1, help_text="If ticked, it means 'is active everywhere - home page requires additional permission.'")),
                ('is_home_active', models.BooleanField(default=1, help_text="If ticked, it means 'is active on home page if is_active status is true'.")),
            ],
        ),
    ]
