# Generated by Django 2.2.2 on 2019-09-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0005_auto_20190909_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qlink',
            name='link_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
