# Generated by Django 2.2.2 on 2019-09-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0006_auto_20190909_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeflyers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flyer', models.ImageField(max_length=255, upload_to='homeflyers/')),
                ('link_src', models.TextField()),
                ('is_active', models.BooleanField(default=1, help_text="If ticked, it means 'is active everywhere - home page requires additional permission.'")),
                ('is_home_active', models.BooleanField(default=1, help_text="If ticked, it means 'is active on home page if is_active status is true'.")),
            ],
        ),
    ]
