# Generated by Django 2.2.2 on 2019-09-10 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0007_homeflyers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homeflyers',
            new_name='Homeflyer',
        ),
    ]
