# Generated by Django 2.2.2 on 2019-09-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name of client', max_length=200)),
                ('last_name', models.CharField(help_text='Last name of client', max_length=200)),
                ('email', models.CharField(blank=True, help_text='Email of client', max_length=200, null=True)),
                ('mobile', models.CharField(help_text='Mobile of client', max_length=200)),
                ('product', models.CharField(help_text='Package/Activity', max_length=200)),
                ('product_id', models.CharField(help_text='Product url', max_length=255)),
                ('adults', models.CharField(max_length=200)),
                ('children', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_signed_up', models.BooleanField(default=0, help_text='Does user hold an account ?')),
                ('user_id', models.IntegerField(blank=True, default=0, help_text='User id, if user has an account', null=True)),
            ],
        ),
    ]
