# Generated by Django 2.2.2 on 2019-09-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_bookingactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_passenger_name', models.CharField(help_text='Full Name of lead passenger', max_length=200)),
                ('mobile', models.CharField(help_text='Contact number', max_length=200)),
                ('email', models.CharField(blank=True, help_text='Email of client', max_length=200, null=True)),
                ('date', models.CharField(help_text='Departure/Activity date', max_length=200)),
                ('adult_tally', models.CharField(help_text='Tally of adult travellers', max_length=200)),
                ('children_tally', models.IntegerField(default=0, help_text='Tally of child travellers')),
                ('adult_expense', models.IntegerField(default=0, help_text='Expense for adults')),
                ('children_expense', models.IntegerField(default=0, help_text='Expense for children')),
                ('gst', models.IntegerField(default=0, help_text='Gst')),
                ('gst_amount', models.IntegerField(default=0, help_text='Gst Amount')),
                ('expense', models.IntegerField(default=0, help_text='Expense excluding gst')),
                ('expense_net', models.IntegerField(default=0, help_text='Net Amount including gst')),
                ('payment_type', models.CharField(help_text='Type of payment - Full or Advance', max_length=200)),
                ('user_id', models.CharField(help_text='User Id', max_length=200)),
                ('booking_uid', models.CharField(help_text='Booking Unique-Id', max_length=200)),
                ('txn', models.CharField(help_text='Transaction number', max_length=200)),
                ('is_confirmation_sent', models.BooleanField(default=0, help_text='If the reply is sent')),
                ('is_vendor_allocated', models.BooleanField(default=0, help_text='Has the vendor/handler been associated.')),
                ('is_new', models.BooleanField(default=0, help_text='Is it a new booking')),
                ('response', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
