# Generated by Django 2.2.2 on 2019-09-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_bookingpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingactivity',
            name='adult_tally',
            field=models.IntegerField(default=0, help_text='Tally of adult travellers'),
        ),
        migrations.AlterField(
            model_name='bookingpackage',
            name='adult_tally',
            field=models.IntegerField(default=0, help_text='Tally of adult travellers'),
        ),
    ]
