# Generated by Django 2.2.2 on 2019-09-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20190910_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingactivity',
            name='user_id',
            field=models.IntegerField(default=0, help_text='User Id'),
        ),
        migrations.AlterField(
            model_name='bookingpackage',
            name='user_id',
            field=models.IntegerField(default=0, help_text='User Id'),
        ),
    ]
