# Generated by Django 2.2.2 on 2019-09-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20190911_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='adults',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='children',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
