# Generated by Django 2.2.2 on 2019-09-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20190914_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='product_url',
            field=models.CharField(blank=True, help_text='Product url', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='product',
            field=models.CharField(blank=True, help_text='Package/Activity', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='product_id',
            field=models.CharField(blank=True, help_text='Product id', max_length=200, null=True),
        ),
    ]
