# Generated by Django 2.2.2 on 2019-09-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20190914_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last name of client', max_length=200, null=True),
        ),
    ]
