# Generated by Django 2.2.2 on 2019-09-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20190914_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='actions_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='is_new',
            field=models.BooleanField(default=1, help_text='New or old'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='is_replied',
            field=models.BooleanField(default=0, help_text='Has query been replied'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='response_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
