# Generated by Django 2.2.2 on 2019-09-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('txn', models.CharField(help_text='Transaction Id', max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookingactivity',
            options={'verbose_name_plural': 'Booked Activities'},
        ),
        migrations.AlterModelOptions(
            name='bookingpackage',
            options={'verbose_name_plural': 'Booked Packages'},
        ),
    ]
