# Generated by Django 2.2.2 on 2019-09-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20190925_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_number',
            new_name='id',
        ),
    ]
