# Generated by Django 2.2.2 on 2019-09-25 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0013_auto_20190925_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adult_count',
            field=models.IntegerField(blank=True, default=0, help_text='Number of adults', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='adult_expense',
            field=models.IntegerField(blank=True, default=0, help_text='Cost per adult', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.IntegerField(blank=True, default=0, help_text='Net Pay', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.CharField(blank=True, help_text='Departure/Activity date', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, help_text='Email of client', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='f_name',
            field=models.CharField(default=0, help_text='First Name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='gst',
            field=models.IntegerField(default=0, help_text='Gst'),
        ),
        migrations.AddField(
            model_name='order',
            name='gst_amount',
            field=models.IntegerField(default=0, help_text='Gst Amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='has_action_taken',
            field=models.BooleanField(default=0, help_text='Has the vendor/handler been associated.'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_new',
            field=models.BooleanField(default=0, help_text='Is it a new booking'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_successfully_paid',
            field=models.BooleanField(default=0, help_text='Is the payment successful'),
        ),
        migrations.AddField(
            model_name='order',
            name='kids_count',
            field=models.IntegerField(blank=True, default=0, help_text='Number of childre', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kids_expense',
            field=models.IntegerField(blank=True, default=0, help_text='Cost per child', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='l_name',
            field=models.CharField(blank=True, help_text='Last Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.CharField(blank=True, help_text='Contact number', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(blank=True, default=0, help_text='Net Pay', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.IntegerField(default=0, help_text='Product Id'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_uid',
            field=models.IntegerField(default=0, help_text='Product UID'),
        ),
        migrations.AddField(
            model_name='order',
            name='productinfo',
            field=models.IntegerField(default=0, help_text='Product Info'),
        ),
        migrations.AddField(
            model_name='order',
            name='response',
            field=models.BooleanField(default=0, help_text='Is the payment successful'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=0, help_text='Net Pay'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Logged in user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(help_text='Order Number', primary_key=True, serialize=False),
        ),
    ]
