# Generated by Django 2.2.2 on 2019-09-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_auto_20190925_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='product',
            new_name='service_code',
        ),
    ]
