# Generated by Django 2.2.2 on 2019-09-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20190926_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_code',
            field=models.CharField(default=0, help_text='Service code of product', max_length=10),
            preserve_default=False,
        ),
    ]
