# Generated by Django 2.2.2 on 2019-09-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_auto_20190926_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_count',
            field=models.IntegerField(blank=True, default=0, help_text='Number of adults', null=True),
        ),
    ]
