# Generated by Django 2.2.2 on 2019-09-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_order_total_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adult_discount_offered',
            field=models.IntegerField(blank=True, default=0, help_text='Discount offered per adult', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kids_discount_offered',
            field=models.IntegerField(blank=True, default=0, help_text='Discount offered per child', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='kids_count',
            field=models.IntegerField(blank=True, default=0, help_text='Number of children', null=True),
        ),
    ]
