# Generated by Django 2.2.2 on 2019-09-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_auto_20190926_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adult_expense',
            new_name='adult_bill',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='kids_expense',
            new_name='kids_bill',
        ),
    ]
