# Generated by Django 2.2.2 on 2019-08-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20190814_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='featured_img_1',
            field=models.ImageField(default=0, max_length=255, upload_to='tourImg/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='featured_img_2',
            field=models.ImageField(default=0, max_length=255, upload_to='tourImg/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='featured_img_3',
            field=models.ImageField(default=0, max_length=255, upload_to='tourImg/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='featured_img_4',
            field=models.ImageField(default=0, max_length=255, upload_to='tourImg/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='featured_img_5',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='tourImg/'),
        ),
        migrations.AddField(
            model_name='package',
            name='featured_title_1',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='featured_title_2',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='featured_title_3',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='featured_title_4',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='featured_title_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_expedition',
            field=models.BooleanField(default=1, help_text='If ticked, it means it is an expedition.'),
        ),
        migrations.AlterField(
            model_name='package',
            name='mention_cities',
            field=models.TextField(help_text='Use same names of cities in citylist. eg: new delhi, chandigarh, manali, ...'),
        ),
    ]
