# Generated by Django 2.2.2 on 2019-08-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20190814_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='featured_img_5',
            field=models.ImageField(default=0, max_length=255, upload_to='tourImg/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='featured_title_5',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
