# Generated by Django 2.2.2 on 2019-08-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_activitysale_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysale',
            name='location',
            field=models.TextField(default=0, help_text='Write the location of the activity or the starting point of the activity.'),
            preserve_default=False,
        ),
    ]
