# Generated by Django 2.2.2 on 2019-08-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_activitysale_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysale',
            name='location',
            field=models.CharField(help_text='Write the location of the activity or the starting point of the activity.', max_length=200),
        ),
    ]
