# Generated by Django 2.2.2 on 2019-08-22 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_auto_20190814_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='home_feature_status',
            field=models.BooleanField(default=1, help_text='If ticked, it means that this sale is fetured on home.'),
        ),
        migrations.AlterField(
            model_name='activitysale',
            name='city',
            field=models.ForeignKey(help_text='If city is not listed then it can be created in profiling or ask admin to create one.', on_delete=django.db.models.deletion.PROTECT, related_name='city', to='profiling.City'),
        ),
        migrations.AlterField(
            model_name='activitysale',
            name='name',
            field=models.ForeignKey(help_text='If activity is not listed then it can be created in profiling or ask admin to create one.', on_delete=django.db.models.deletion.PROTECT, related_name='name', to='profiling.Activity'),
        ),
    ]
