# Generated by Django 2.2.2 on 2019-08-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_auto_20190823_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='dates',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
