# Generated by Django 2.2.2 on 2019-08-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_auto_20190829_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='costingprize_per_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='generalprize_per_children',
            field=models.IntegerField(default=0),
        ),
    ]
