# Generated by Django 2.2.2 on 2019-08-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_auto_20190829_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='costingprize_per_children',
            new_name='costingprize_per_child',
        ),
        migrations.RemoveField(
            model_name='package',
            name='generalprize_per_children',
        ),
        migrations.AddField(
            model_name='package',
            name='generalprize_per_child',
            field=models.IntegerField(default=0),
        ),
    ]
