# Generated by Django 2.2.2 on 2019-08-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_auto_20190830_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='gst',
            field=models.IntegerField(default=5),
        ),
    ]
