# Generated by Django 2.2.2 on 2019-08-31 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_package_gst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='discount',
            new_name='dicount_pax2',
        ),
    ]
