# Generated by Django 2.2.2 on 2019-08-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_auto_20190831_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='dicount_pax2',
            new_name='discount_pax2',
        ),
        migrations.RemoveField(
            model_name='package',
            name='costingprize_per_adult',
        ),
        migrations.AddField(
            model_name='package',
            name='discount_pax4',
            field=models.IntegerField(default=0),
        ),
    ]
