# Generated by Django 2.2.2 on 2019-08-31 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_auto_20190831_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='costingprize_per_child',
        ),
    ]
