# Generated by Django 2.2.2 on 2019-08-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0019_auto_20190831_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='dates',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='discount_max',
            field=models.IntegerField(default=0, help_text='Discount applicable for more than 8 individuals.'),
        ),
        migrations.AlterField(
            model_name='package',
            name='discount_pax2',
            field=models.IntegerField(default=0, help_text='Discount applicable for min 2 individuals.(1 adult + 1 child) or 2 adults; on their rspective charges.'),
        ),
        migrations.AlterField(
            model_name='package',
            name='discount_pax4',
            field=models.IntegerField(default=0, help_text='Discount applicable for min 4 individuals.'),
        ),
        migrations.AlterField(
            model_name='package',
            name='discount_pax6',
            field=models.IntegerField(default=0, help_text='Discount applicable for min 6 individuals.'),
        ),
        migrations.AlterField(
            model_name='package',
            name='discount_pax8',
            field=models.IntegerField(default=0, help_text='Discount applicable for min 8 individuals.'),
        ),
    ]
