# Generated by Django 2.2.2 on 2019-09-06 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0002_auto_20190906_1450'),
        ('tours', '0020_auto_20190901_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='itinerary',
            field=models.ForeignKey(default=1, help_text='Select or Create Itinerary.', on_delete=django.db.models.deletion.PROTECT, related_name='itinerary', to='props.Itinerary'),
            preserve_default=False,
        ),
    ]
