# Generated by Django 2.2.2 on 2019-09-06 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0021_package_itinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='itinerary',
            field=models.ForeignKey(help_text='Select or Create Itinerary.', on_delete=django.db.models.deletion.PROTECT, related_name='refrence', to='props.Itinerary'),
        ),
    ]
