# Generated by Django 2.2.2 on 2019-09-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0024_auto_20190918_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration_days',
            field=models.IntegerField(default=1, help_text='Trip days'),
        ),
    ]
