# Generated by Django 2.2.2 on 2019-09-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0025_package_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysale',
            name='slug',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
