# Generated by Django 2.2.2 on 2019-09-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0026_activitysale_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysale',
            name='slug',
            field=models.CharField(default='--url-slug--', max_length=200),
        ),
    ]
