# Generated by Django 2.2.2 on 2019-09-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0027_auto_20190922_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysale',
            name='activitypoint',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitysale',
            name='mapembeed',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
