# Generated by Django 2.2.2 on 2019-09-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0029_auto_20190923_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysale',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
