# Generated by Django 2.2.2 on 2019-09-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0035_auto_20190923_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysale',
            name='uid',
            field=models.CharField(default='21be5003', max_length=200, unique=True),
        ),
    ]
