# Generated by Django 2.2.2 on 2019-09-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0036_auto_20190923_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='uid',
            field=models.CharField(default='--uid--', max_length=200),
        ),
        migrations.AlterField(
            model_name='activitysale',
            name='slug',
            field=models.CharField(default='--url-slug--', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='activitysale',
            name='uid',
            field=models.CharField(default='--uid--', max_length=200, unique=True),
        ),
    ]
