# Generated by Django 2.2.2 on 2019-09-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0037_auto_20190923_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='url_title',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
