# Generated by Django 2.2.2 on 2019-09-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0038_auto_20190923_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='uid',
            field=models.CharField(default='--uid--', max_length=200, unique=True),
        ),
    ]
