# Generated by Django 2.2.2 on 2019-09-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0039_auto_20190923_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='are_children_allowed',
            field=models.BooleanField(default=0, help_text='Tick if children allowed.'),
        ),
    ]
