# Generated by Django 2.2.2 on 2019-09-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0040_package_are_children_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysale',
            name='service_code',
            field=models.CharField(default='act', max_length=10),
        ),
        migrations.AddField(
            model_name='package',
            name='service_code',
            field=models.CharField(default='pak', max_length=10),
        ),
    ]
