# Generated by Django 2.2.2 on 2019-09-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0041_auto_20190926_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='service_code',
            field=models.CharField(default='pac', max_length=10),
        ),
    ]
