# Generated by Django 2.2.2 on 2019-09-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0044_auto_20190928_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysale',
            name='thumb',
            field=models.ImageField(help_text='Ideal dimensions 300 x 240', max_length=255, upload_to='thumbs'),
        ),
        migrations.AlterField(
            model_name='package',
            name='thumb',
            field=models.ImageField(help_text='Ideal dimensions 300 x 240', max_length=255, upload_to='thumbs'),
        ),
    ]
