# Generated by Django 2.2.2 on 2019-09-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0045_auto_20190928_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysale',
            name='duration',
            field=models.CharField(default='0 hrs', help_text='Mention Clear Durataion in minutes or hours or days. Eg: 15 minutes', max_length=200),
        ),
        migrations.AlterField(
            model_name='activitysale',
            name='location',
            field=models.CharField(help_text="Write the location name to create a unique url eg: 'Greater Akshardhaam Rafting Point' it will make url as '.../greater-akshardhaam-rafting-point/' only once. ", max_length=200),
        ),
    ]
