# Generated by Django 2.2.2 on 2019-09-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0046_auto_20190929_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysale',
            name='make_exclusive',
            field=models.BooleanField(default=0, help_text='For exclusive packages.'),
        ),
        migrations.AddField(
            model_name='activitysale',
            name='make_inbudget',
            field=models.BooleanField(default=0, help_text='For budget packages.'),
        ),
        migrations.AddField(
            model_name='activitysale',
            name='make_indemand',
            field=models.BooleanField(default=0, help_text='For in demand packages.'),
        ),
        migrations.AddField(
            model_name='activitysale',
            name='make_limitedoffer',
            field=models.BooleanField(default=0, help_text='For limited packages.'),
        ),
    ]
