# Generated by Django 2.2.2 on 2019-09-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0048_auto_20190929_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysale',
            name='home_feature_status',
            field=models.BooleanField(default=0, help_text='If ticked, it means that this sale is fetured on home in Pins.'),
        ),
        migrations.AlterField(
            model_name='package',
            name='home_feature_status',
            field=models.BooleanField(default=1, help_text='If ticked, it means that this sale is fetured on home in Pins.'),
        ),
    ]
