# Generated by Django 2.2.2 on 2019-08-14 16:58

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('land', 'Land Activity'), ('water', 'Water Activity'), ('air', 'Air Activity'), ('other', 'Other Activity')], default='India', max_length=100)),
                ('thumb', models.ImageField(max_length=255, upload_to='activity/')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Unique code for country.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('slug', models.CharField(default='--slug--', max_length=100)),
                ('intro', models.TextField(null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(help_text='Article body')),
                ('country', models.CharField(choices=[('India', 'India'), ('Sri Lanka', 'Sri Lanka')], default='India', max_length=100)),
                ('advisory', models.TextField(blank=True, null=True)),
                ('disclaimer', models.TextField(blank=True, null=True)),
                ('featured_img_1', models.ImageField(max_length=255, upload_to='city/')),
                ('featured_title_1', models.CharField(max_length=200, null=True)),
                ('featured_img_2', models.ImageField(max_length=255, upload_to='city/')),
                ('featured_title_2', models.CharField(max_length=200, null=True)),
                ('featured_img_3', models.ImageField(max_length=255, upload_to='city/')),
                ('featured_title_3', models.CharField(max_length=200, null=True)),
                ('featured_img_4', models.ImageField(max_length=255, upload_to='city/')),
                ('featured_title_4', models.CharField(max_length=200, null=True)),
                ('featured_img_5', models.ImageField(blank=True, max_length=255, null=True, upload_to='city/')),
                ('featured_title_5', models.CharField(blank=True, max_length=200, null=True)),
                ('featured_img_6', models.ImageField(blank=True, max_length=255, null=True, upload_to='city/')),
                ('featured_title_6', models.CharField(blank=True, max_length=200, null=True)),
                ('featured_img_7', models.ImageField(blank=True, max_length=255, null=True, upload_to='city/')),
                ('featured_title_7', models.CharField(blank=True, max_length=200, null=True)),
                ('featured_img_8', models.ImageField(blank=True, max_length=255, null=True, upload_to='city/')),
                ('featured_title_8', models.CharField(blank=True, max_length=200, null=True)),
                ('keywords', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country', to='profiling.Country')),
            ],
        ),
    ]
