# Generated by Django 2.2.2 on 2019-08-14 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='category',
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country', to='profiling.Country'),
        ),
    ]
