# Generated by Django 2.2.2 on 2019-08-22 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_auto_20190814_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
