# Generated by Django 2.2.2 on 2019-09-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0004_activity_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='banner',
            field=models.ImageField(default=0, max_length=255, upload_to='activity/banners'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='thumb',
            field=models.ImageField(max_length=255, upload_to='activity/thumbs'),
        ),
    ]
