# Generated by Django 2.2.2 on 2019-09-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0005_auto_20190911_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='banner',
            field=models.ImageField(help_text='900 x 300', max_length=255, upload_to='activity/banners'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='thumb',
            field=models.ImageField(help_text='200 x 200', max_length=255, upload_to='activity/thumbs'),
        ),
    ]
