# Generated by Django 2.2.2 on 2019-09-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0006_auto_20190914_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('thumb', models.ImageField(help_text='Ideal dimaensions 300 x 240', max_length=255, upload_to='thumbs')),
                ('path1', models.CharField(blank=True, max_length=200, null=True)),
                ('path2', models.CharField(blank=True, max_length=200, null=True)),
                ('path3', models.CharField(blank=True, max_length=200, null=True)),
                ('path4', models.CharField(blank=True, max_length=200, null=True)),
                ('labels', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('service_time', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('keywords', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Indeces',
            },
        ),
    ]
