# Generated by Django 2.2.2 on 2019-09-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0007_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='ref_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='index',
            name='ref_service_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='index',
            name='ref_uid',
            field=models.CharField(default='', max_length=10),
        ),
    ]
