# Generated by Django 2.2.2 on 2019-09-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0008_auto_20190928_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='labels',
        ),
        migrations.AddField(
            model_name='index',
            name='make_exclusive',
            field=models.BooleanField(default=0, help_text='For exclusive packages.'),
        ),
        migrations.AddField(
            model_name='index',
            name='make_inbudget',
            field=models.BooleanField(default=0, help_text='For budget packages.'),
        ),
        migrations.AddField(
            model_name='index',
            name='make_indemand',
            field=models.BooleanField(default=0, help_text='For in demand packages.'),
        ),
        migrations.AddField(
            model_name='index',
            name='make_limitedoffer',
            field=models.BooleanField(default=0, help_text='For limited packages.'),
        ),
        migrations.AlterField(
            model_name='index',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='ref_id',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='ref_service_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='ref_uid',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='service_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='thumb',
            field=models.ImageField(blank=True, help_text='Ideal dimaensions 300 x 240', max_length=255, null=True, upload_to='thumbs'),
        ),
        migrations.AlterField(
            model_name='index',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
