# Generated by Django 2.2.2 on 2019-09-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0009_auto_20190929_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='is_listed',
            field=models.BooleanField(default=0, help_text='For budget packages.'),
        ),
    ]
