# Generated by Django 2.2.2 on 2019-09-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0010_index_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='home_feature_status',
            field=models.BooleanField(default=0, help_text='Is Running on Home.'),
        ),
        migrations.AlterField(
            model_name='index',
            name='is_listed',
            field=models.BooleanField(default=0, help_text='Is Running on website'),
        ),
    ]
